### ISSUE TITLE
Can we live without pytest-test-runner?

### ISSUE THREAD

**Issue by irl** [mikeperry-tor/vanguards#15]
pytest-test-runner is not well maintained in Debian. The tests can be run by calling pytest separately instead of via setup.py. This would simplify packaging for Debian and probably also for other platforms.

**Comment by mikeperry-tor** [comment]
Yeah. Tbh I cargo-culted a lot of that setup.py boilerplate. If you want to run pytest another way, just go ahead and patch it to be what you need.

In fact, I only really care about the tox testing pathway, since those are used by travis and are what I also run locally. I don't ever directly rely on setup.py testing...
