### ISSUE TITLE
Don't write torrc by default

### ISSUE THREAD

**Issue by irl** [mikeperry-tor/vanguards#18]
In Debian, the debian-tor user is not able to write to the torrc.

```
-rw-r--r-- 1 root root 10455 Mar  2 12:24 /etc/tor/torrc
```

**Comment by asn-d6** [comment]
Hmm, according to irl this seems to trigger:
```
 NOTICE[Mon Jul 30 15:33:22 2018]: Tor can't save its own config file: Unable to write configuration to disk.
```

From looking at the code, this might be OK because the config is still saved in the state file in `new_consensus_event()`.

Then the state file is read upon startup in `main()` before `new_consensus_event()`  gets called, so it should always have the right info.

If I'm right, this means that this error is not terrible and vanguards should work fine. If I'm right (Mike?), then we might consider reducing the severity of that log, or just killing the torrc writing functionality altogether (What is it for, since we have a state file?).

Mike, what do you think?

**Comment by mikeperry-tor** [comment]
Yeah it's definitely harmless with respect to the code. As for not writing to Torrc, I can see one argument for, and one against.

For: If we write to torrc, then there is no risk of service races or service restart that allow the Tor instance to make onion service paths outside of the vanguard set. (This can happen if Tor restarts and vanguards is not -- the vanguards instance will go away because the control connection died.. Maybe this is a bug itself though.. but what is the fix? Keep trying to connect so long as we're alive?)

Against: Writing to the torrc file won't work in situations like this. But perhaps worse, when it does work, users who try out vanguards and then decide not to use it get these HSLayer lines added to their torrc. If a full layer worth of guards goes down, then their Tor will stop building onion service circuits entirely. 

So is this worse? Is the safety worth the surprise side effects against some users? Is writing to the torrc file even the best/right way to provide this safety? Maybe we should try more aggressively to connect to Tor? Maybe systemd can ensure we're always running if Tor is?

Personally I'm leaning towards removing this torrc writing (or making it optional and off by default, or perhaps via an --update-tor-only one-shot option) because I think the risk in terms of confusing users with side effects is worse. What do you folks think about the service dependency issues?

**Comment by irl** [comment]
> the vanguards instance will go away because the control connection died

Uh oh! This is definitely a bug in my opinion.

It is possible to restart the service if it exits, but this will only happen so many times before systemd decides it's not going to start again.

I would prefer it if vanguards were to try to reconnect quite aggressively in the case that it is disconnected.

**Comment by mikeperry-tor** [comment]
Ok torrc writing is now disabled. I am convinced that it makes more sense to just try to reconnect aggressively.

I added a --one_shot_vanguards option that just writes/updates torrc and then exits, for people who don't want this thing to be running all the time. (They can call it periodically from cron or something).
