### ISSUE TITLE
CIRC event had an unrecognized remote_reason

### ISSUE THREAD

**Issue by traumschule** [mikeperry-tor/vanguards#31]
Please handle
- CHANNEL_CLOSED
- HS_CLIENT_HSDIR
- HS_SERVICE_HSDIR
- HS_VANGUARDS

Caught several of these:
```
INFO:stem:CIRC event had an unrecognized remote_reason (CHANNEL_CLOSED). Maybe a new addition to the control protocol? Full Event: 'CIRC 347 FAILED $relay,$relay,NEED_CAPACITY PURPOSE=TESTING TIME_CREATED=2018-08-25T02:48:19.546319 REASON=DESTROYED REMOTE_REASON=CHANNEL_CLOSED'
INFO:stem:CIRC event had an unrecognized purpose (HS_CLIENT_HSDIR). Maybe a new addition to the control protocol? Full Event: 'CIRC 472 LAUNCHED BUILD_FLAGS=IS_INTERNAL,NEED_CAPACITY PURPOSE=HS_CLIENT_HSDIR HS_STATE=HSCI_CONNECTING TIME_CREATED=2018-08-25T02:50:03.529166'
INFO:stem:CIRC_MINOR event had an unrecognized old_purpose (HS_SERVICE_HSDIR). Maybe a new addition to the control protocol? Full Event: 'CIRC_MINOR 150 PURPOSE_CHANGED $relay,$relay,$relay,NEED_CAPACITY PURPOSE=MEASURE_TIMEOUT TIME_CREATED=2018-08-25T03:10:53.505273 OLD_PURPOSE=HS_SERVICE_HSDIR OLD_HS_STATE=HSSI_CONNECTING'
INFO:stem:CIRC_MINOR event had an unrecognized old_purpose (HS_VANGUARDS). Maybe a new addition to the control protocol? Full Event: 'CIRC_MINOR 175 PURPOSE_CHANGED $relay,$relay,$relay,$relay,NEED_CAPACITY,NEED_UPTIME PURPOSE=HS_SERVICE_HSDIR HS_STATE=HSSI_CONNECTING TIME_CREATED=2018-08-25T03:10:58.927978 OLD_PURPOSE=HS_VANGUARDS'

**Comment by mikeperry-tor** [comment]
These log messages are from stem. They are harmless, since we do not use keywords for these values, we use the direct string.

Out of curiosity, what is your stem version? I just pushed 7d79823f4e4cc4e157e75954492f80b2c9172212 to aid in debugging any issues that might arise from this.

Also, with your stem version, I can pin that in the unit tests and look for any issues (currently tox pins stem at 1.5.4).

You can also try one of the last two testing methods outside of Tox to ensure that the system-wide stem passes tests against either the git checkout or a system-wide vanguards install:
https://github.com/mikeperry-tor/vanguards/blob/master/README_TESTS.md

**Comment by mikeperry-tor** [comment]
I tested Stem 1.6.0 against the unit tests and there are no ill effects due to these info messages.

If you notice any, please open specific bugs.
