### ISSUE TITLE
Rate limit Introduce2 circuits or force-close circuits with long build times?

### ISSUE THREAD

**Issue by Obire** [mikeperry-tor/vanguards#42]
Current unpreventable attacks are possible due to lots of Introduce2 cells being sent with the client not needing to verify, which results in extremely long build times which cannot be closed fast enough because of graceful closure. Is it possible to add within vanguards a way of rate limiting Introduce2 cells or simply allowing the force close of circuits with build times that exceed X (value configured within vanguards config)?

This would be perfect and an instant fix right now if something like this would be possible to introduce into this project.

**Comment by Obire** [comment]
The circuit building causes the Tor process CPU to be pinned at 100%, rendering it unresponsive and seems to be from the crypto libraries used for circuit building.

**Comment by mikeperry-tor** [comment]
Unfortunately due to how Introduce requests work, rate limiting them (presumably by closing the circuit -- that's the only lever I have at the control port level) would just cause whatever fraction of requests to take longer or fail. I am not sure it would actually improve your situation.

However, have you seen https://trac.torproject.org/projects/tor/ticket/30291 and its children? It looks like the upcoming 0.4.1 alpha release will have performance improvements for this case. The 0.4.1 series will have its first alpha shortly after May 15th, and will stabilize around August: https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases#Calendar:

You can also built current Tor master and try that out, or try to backport those child tickets yourself...

**Comment by mikeperry-tor** [comment]
Also relevant: https://trac.torproject.org/projects/tor/ticket/15516 (needs child tickets to be completed first before it is useful).

Roger's point on that ticket is interesting: if the attacker's client is well-behaved, then closing over-used INTRODUCE circuits in vanguards might slow it down. But services would also still suffer from availability loss while under attack. So trying to solve this in vanguards alone seems like it would not satisfy https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle -- it might work for a while, but the adversary could adapt and still find ways to keep services down.

If someone wants to try it anyway to conduct some experiments, the implementation would be very similar to the MAX_HSDESC_KILOBYTES option, except instead of checking for circuits with purpose HS_SERVICE_HSDIR, the check would be for purpose HS_SERVICE_INTRO:
https://github.com/mikeperry-tor/vanguards/blob/12f1dcc9b9584edcc45cba86b3e0a00a0d829c1a/src/vanguards/bandguards.py#L238

In fact, a one-line hack that changes HS_SERVICE_HSDIR to HS_SERVICE_INTRO there would cause the MAX_HSDESC_KILOBYTES option to apply to introduce2 cells, causing the client to close introduce circuits after so many kilobytes. 

Again, I think that's not likely to work well, so I'm not going to bother with trying that experiment myself, but I've been surprised before.

**Comment by Obire** [comment]
Thanks for that Mike, it seemingly works when the Tor process is restarted, closing a lot of the attacking circuits, however it is still overwhelmed pretty quickly to 100% CPU.

Is there anything else you could recommend which could make it more "aggressive" as such?

**Comment by mikeperry-tor** [comment]
The Tor Control Port is limited in what it can do. The only thing it can do in this case is close the circuits more often, which will cause you to randomly drop more intro requests and not build as many rend circuits. If you lower that MAX_HSDESC_KILOBYTES config setting after editing that line, it will close the circuit and log at that lower limit.

Out of curiosity, when you test this, do you see any NOTICE messages in vanguards log about relay overuse? This is relevant to Issue #38 and might also shed light on this problem.

**Comment by mikeperry-tor** [comment]
I am also curious if the vanguards process itself exhibits high CPU load under these conditions.

**Comment by Obire** [comment]
I'll update you with the outputs shortly, when I lowered the MAX_HSDESC_KILOBYTES setting it didn't seem to take effect, not sure if it isn't following the config file for some reason.

Vanguards CPU is often pretty high around 120-140, but I attributed that mostly to the fact I wasn't using pypy.

**Comment by mikeperry-tor** [comment]
Vanguards itself might be overloaded and not closing the circuits fast enough. If it is hitting 100% CPU itself you should definitely consider pypy. 100% CPU means that it will be delayed in responding to any limit overages, which may impact your results.

But it should still close circuits eventually... The setting is actually named circ_max_hsdesc_kilobytes in the vanguards.conf file, under the [Bandguards] section. Are you sure you're loading the config?

**Comment by Kirtaner** [comment]
I'm prepping to launch a tor mirror of one of my large communities and I've been doing testing with an HS_SERVICE_INTRO addition, it actually does help keep the service reachable far longer than normal.

> When you tested this, did you see any NOTICE log messages in vanguards log about any relays being used "above its consensus weight" (direct quote from log)? This is relevant to Issue #38 and might also shed light on this problem.

I personally have not

**Comment by mikeperry-tor** [comment]
Very interesting. This could be broken out into a separate config option and check on its own then, if it is proving effective in DoS defense. I removed the needs testing flag to reflect that this seems to help in testing.

**Comment by mikeperry-tor** [comment]
Ok this option is now provided and documented in the conf file, README_TECHNICAL.md, and changelog.
