### ISSUE TITLE
Improve options documentation

### ISSUE THREAD

**Issue by mikeperry-tor** [mikeperry-tor/vanguards#55]
See https://trac.torproject.org/projects/tor/ticket/33648

**Comment by gits7r** [comment]
Yes, while the README_SECURITY and README_TECHNICAL are amazing, more explanation is needed for some options in the configuration file.

For example, I was just testing now vangaurds concurrently with onionbalance, and I was confused by this line:

https://github.com/mikeperry-tor/vanguards/blob/b6eceb2e99e46a00563e7dd055096c5e82a7fd60/vanguards-example.conf#L53

It reads: "How long to keep our layer1 guard (0 means use Tor default)", but the example comes with a 2-3-8 topology by default. So, this means that the vanguards system is adding another entry guard to Tor, like edit torrc and add NumEntryGuards 2 ? The questions that appear here are:

- What happens if the Tor instance is using just a bridge? How is the 2-3-8 topology respected then, should users change `num_layer1_guards = 1` in this case? 
- What if someone has more bridges in their torrc (say at least 2) should these users set `num_layer1_guards = 2`  and assume vanguard system will treat them as layer 1 guards?

`one_shot_vanguards = False` is vague, does it mean that a layer 2 or layer 3 guard is rotated immediately after first circuit failed to build? What is the retry logic if a layer 2 or layer 3 guard goes offline?

I'll be happy to write it explicitly if you give me short answers.

**Comment by mikeperry-tor** [comment]
> Yes, while the README_SECURITY and README_TECHNICAL are amazing, more explanation is needed for some options in the configuration file.
> 
> For example, I was just testing now vangaurds concurrently with onionbalance, and I was confused by this line:
> 
> https://github.com/mikeperry-tor/vanguards/blob/b6eceb2e99e46a00563e7dd055096c5e82a7fd60/vanguards-example.conf#L53
> 
> It reads: "How long to keep our layer1 guard (0 means use Tor default)", but the example comes with a 2-3-8 topology by default. So, this means that the vanguards system is adding another entry guard to Tor, like edit torrc and add NumEntryGuards 2 ? The questions that appear here are:
> 
>     * What happens if the Tor instance is using just a bridge? How is the 2-3-8 topology respected then, should users change `num_layer1_guards = 1` in this case?

If Tor is configured to use a bridge, the num_layer1_guards setting will be ignored and the number of bridges you have will be used instead. This should be clarified.

>     * What if someone has more bridges in their torrc (say at least 2) should these users set `num_layer1_guards = 2`  and assume vanguard system will treat them as layer 1 guards?

Hrm, I don't think there is currently a way to configure more bridges than Tor will use at once... Whatever is configured, Tor will use.

> `one_shot_vanguards = False` is vague, does it mean that a layer 2 or layer 3 guard is rotated immediately after first circuit failed to build? What is the retry logic if a layer 2 or layer 3 guard goes offline?

one_shot_vanguards is meant for use hourly from cron. All it does is choose nodes to specify in HSLayer2Nodes and HSLayer3Nodes torrc option. If those nodes go down, they will stop being used. If all of the nodes go down in a layer, Tor will no longer make circuits. In other words, it fails closed. This was a deliberate design choice.
> I'll be happy to write it explicitly if you give me short answers.

**Comment by mikeperry-tor** [comment]
See also https://trac.torproject.org/projects/tor/ticket/33815 for other questions/clarifications

**Comment by mikeperry-tor** [comment]
Fixed and documented in changelog. Closing this.
